# This is a basic workflow to help you get started with Actions

name: Hexo Deploy CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the server branch
  push:
    branches: [server]
  pull_request:
    branches: [server]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set Git configuration variables
        run: |
          git config --global user.name "niemingzhao"
          git config --global user.email "1432440963@qq.com"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: |
          npm install -g hexo-cli
          npm ci
          npm install qiniu

      - name: Hexo generate
        run: hexo generate --force

      - name: Hexo deploy
        run: |
          sed -i "s~git@github.com:~https://${{secrets.gh_token}}@github.com/~" _config.yml
          hexo deploy > /dev/null
          node qupload.js ${{secrets.qn_ak}} ${{secrets.qn_sk}} Zone_z0 hexo-site https://www.niemingzhao.top
